version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resource-db
    ports:
      - '5432:5432'
    volumes:
      - resource-db-data:/var/lib/postgresql/data
  localstack:
    image: localstack/localstack:1.3.1
    environment:
      - SERVICES=s3
      - ACCESS_KEY=local-dev-access-key
      - SECRET_KEY=local-dev-secret-key
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
    ports:
      - "4571:4571"
      - "4572:4572"
      - "4566:4566"
    volumes:
      - "resource-s3-data:/tmp/localstack/data"
volumes:
  resource-db-data:
    driver: local
  resource-s3-data:
    driver: local
